## Draws three beta distribution
```{r}
shapes <- function(shape1, shape2,...) {
x <- seq(0,1,length=100)
plot(0:0,ylim = c(0,5), xlim = c(0,1), xlab = "x", ylab = "Prob Density")
lines(x, dbeta(x, shape1 = shape1, shape2 = shape2), ...)
lines(x, dbeta(x, shape1 = 1, shape2 = 4), lwd=2, col = "green")
lines(x, dbeta(x, shape1 = 4, shape2 = 2), lwd=3)
}
shapes(3,1, lwd = 5, col = "red")
```

## Draws a beta distribution
``` {r eval=FALSE}
drawBeta <- function(a,b,...){
x <- seq(0,1,length=100)
plot(0:0,ylim = c(0,5), xlim = c(0,1), xlab = "x", ylab = "Prob Density")
lines(x, dbeta(x, shape1 = a, shape2 = b), ...)
}
betaApp <- function(pts){
  manipulate({drawBeta(a,b,col = color, lwd=lwd); points(pts,rep(0,length(pts)))},
    a = slider(0,10,initial=1,"a", .2),
    b = slider(0,10,initial=2,"b", .2),
    color = picker(as.list(colors())),
    lwd = slider(0,10,initial=.5,"lwd",1)
  )
}

```

``` {r}
ballistics <- function(v, theta, h) {
  x <- seq(0,1, length=100)
  plot(0:0,xlim = c(0,50), ylim = c(0,50), xlab = "Horizontal Distance", ylab = "Vertical Distance", type = "n")
  horizontalDistance <- (v * cos(theta))/-9.8* (v * sin(theta) + sqrt((v * sin(theta))^2+(2*-9.8*h)))
  lines(x,horizontalDistance, col = "red")
    
}
App <- function() {
  manipulate({ballistics(v,theta,h)},
             v <- slider(0,50, initial = 1, label = "velocity", step = 1),
             theta <- slider(0,pi/2, initial = pi/8, label = "Launch angle", step = pi/8),
             h <- slider(0,50, initial = 1, label = "Initial hieght", step = 1)
             )
}
```