# NOT DONE

``` {r}
addEm <- function(v) {
  sum <- 0  #accumulator
  for( k in 1:length(v) ) {
    sum <- sum + v[k]
  }
return(sum)
  }
addEm(1:5)
```

``` {r}
newAddEm <- function(v) {
  if (length(v)==0) return(0)
  return( v[1] + newAddEm(v[-1]))
  }
newAddEm(1:5)
```

## ??
``` {r}
fibLoop <- function(n) {
    
}
```

``` {r}
fibRecurse <- function(n) {
    # handle the cases that are really simple
    if (n == 1) {
        return(1)
    } else {
        if (n == 0) 
            return(0)
    }
thisF <- fibRecurse(n - 1) + fibRecurse(n - 2)
    # Return the answer assembled from the simple bits
    return(thisF)
}  
fibRecurse(4)
```


``` {r}
addNSeq <- function(n) {
  if (n == 1) return(n)
  else {
    sum <- c(n, addNSeq(n-1))
  }
  return(sum(sum))
  }
addNSeq(5)
```

```{r}
addNLoop <- function(n) {
  sum <- c()
  for (k in n:0) {
    sum <- c(sum, k)
    k <- k-1
  }
 
  return(sum(sum))
  }
addNLoop(5)
```

# ??
``` {r}
addRecur <- function(v) {
  if (length(v) == 1) return(v)
  else {
    ans <- c(v[1] + addRecur(v[-1]))
  }
  return(ans)
  }
addRecur(c(5,4,3,2,1))
```

#??
``` {r}
addRecurLoop <- function(x) {
  sum <- c()
  l <- length(x)
  while (x > x[l]) {
    sum <- c(sum, x)
    x <- x-1
  }
  return(sum)       
}
addRecurLoop(c(5))
```

# NOT FINISHED