

```{r}
outliers <- function(x) {
  a <- quantile(x)[2] 
  b <- quantile(x)[4] 
  as.logical(x<a | x>b)
  
}
outliers(1:10)
```

```{r}
EnglishNumbers <-  c("zero","one", "two", "three", "four")
numToText <- function(num,lang) {
  ans <- lang[num+1]
  return(ans)
  }
numToText(2,EnglishNumbers)
```

``` {r}
EnglishNumbers <-  c("zero","one", "two", "three", "four")
TextToNum <- function(word,lang) {
  ans = which(lang == word)
  return(ans-1)
}
TextToNum("three", EnglishNumbers)
```



``` {r}
digitToWord <- function(integer,language) {
  if (language == "English") {
    if (integer == "0") print("zero")
    if (integer == "1") print("one")
    if (integer == "2") print("two")
    if (integer == "3") print("three")
    if (integer == "4") print("four")
    if (integer == "5") print("five")
    if (integer == "6") print("six")
    if (integer == "7") print("seven")
    if (integer == "8") print("eight")
    if (integer == "9") print("nine")
  }
  if (language == "Spanish"){
    if (integer == "0") print("cero")
    if (integer == "1") print("uno")
    if (integer == "2") print("dos")
    if (integer == "3") print("tres")
    if (integer == "4") print("cuatro")
    if (integer == "5") print("cinco")
    if (integer == "6") print("seis")
    if (integer == "7") print("siete")
    if (integer == "8") print("nueve")
    if (integer == "9") print("niete")
  }
  if (language == "French"){
    if (integer == "0") print("zero")
    if (integer == "1") print("un")
    if (integer == "2") print("deux")
    if (integer == "3") print("trois")
    if (integer == "4") print("quatre")
    if (integer == "5") print("cinq")
    if (integer == "6") print("six")
    if (integer == "7") print("sept")
    if (integer == "8") print("huit")
    if (integer == "9") print("neuf")
  }
}

digitToWord("5", "Spanish")
digitToWord("1", "English")
digitToWord("9", "French")
```



``` {r}
v <- c("apple", "berry", "carrie", "rr")
lettersMatch <- function(words,pattern) {
  a = grep(pattern,words)
  
  return(v[a])
  }
lettersMatch(v, "rr" )
```

``` {r}
piSeries <- function(n) {
  k <- 1:n
  series <- ((-1)^(k+1)/(2*k-1))
  return(4*(sum(series)))
  }
piSeries(11)
```


``` {r}
other <- function(n) {
  sum <- 1
  num <- 1
  for (k in 3:n) {
    if (n%%2 == 1){
    sum <- sum + (-1/k)*(num)
    num <- num*-1
    }
  }
  return(sum*4)
}
  
other(30)
```


``` {r}
howCloseToPi <- function(n) {
  k <- 1:n
  y <- sapply(k, FUN = piSeries)
  plot(k, y, xlab = "n", ylab = "y")
}
howCloseToPi(100)
```